# Generated by Django 5.1 on 2024-08-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_at',
        ),
    ]
